openapi: 3.0.0
info:
  title: bizzabo
  version: 0.1.0

servers:
  - url: http://localhost:8080/api/v1

tags: []

paths: {}

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  responses:
    ErrorResponse:
      description: Something went awfully wrong.
      content:
        application/json:
          schema:
            type: object
            properties:
              timestamp:
                type: string
                format: date-time
                example: 2023-04-15T12:30:45.990Z
              status:
                type: integer
                example: 500
              error:
                type: string
                example: Internal Server Error
              message:
                type: string
                example: Something went awfully wrong.
              path:
                type: string
                example: /v1/api/**
